title: Salesforce Developer Group Tokyo
description: Force.comやHerokuなど、Salesforce Platformを使って開発する開発者の情報共有と交流のためのグループ
lang: ja

url: https://sfdg.tokyo
author: Salesforce Developer Group Tokyo
logo: assets/img/logo.jpg
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:year-:month-:day-:title/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Articles
   url: /articles
 - title: Meetup
   url: https://www.meetup.com/ja-JP/preview/Tokyo-Salesforce-Developer-Group
 - title: Trailblazer Community
   url: https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000001oWJ
 - title: About
   url: /about

social:
   github: sfdgtokyo
   twitter: SfdgTokyo
   facebook: groups/salesforcedugjapan
   name: Salesforce Developer Group Tokyo
   links:
     - https://github.com/sfdgtokyo
     - https://twitter.com/SfdgTokyo
     - https://www.facebook.com/groups/salesforcedugjapan

twitter:
  username: SfdgTokyo

google_analytics: "UA-109185178-1"
